### PR TITLE
Include fields with a value of zero in the percentage calculation

### PR DESCRIPTION
**Pull request by grahamgilchrist**
This PR adjusts the percentage complete calculation to include questions which have a legitimate answer of the number zero.

Another effect of this change, is that questions answered as a blank string are now counted when they weren't before.

### CODE REVIEW

**Comment by grahamgilchrist** [comment]
@incuna/js Pls review/merge

**Comment by wytrych** [comment]
Would be nice to add a test for that

**Comment by wytrych** [comment]
Nice, HWTI

**Comment by grahamgilchrist** [comment]
Good idea. I'm not sure if we should be counting empty strings, but at least with the test we make the behaviour explicit and known.

**Pull request merged**
