### PR TITLE
Change multi slider heading to span to match other heading style

### PR DESCRIPTION
**Pull request by brynley**
Needed for https://github.com/incuna/incuna-optimise/pull/414

@incuna/frontend Please can someone review 👾

### CODE REVIEW

**Comment by hippogriffic** [comment]
I think you'll need to run grunt to compile the templates and commit those :)

**Comment by hippogriffic** [comment]
looks like you've got an excited js test fail too :(

**Comment by Minglee01** [comment]
Check the failed test might just b looking for a h4

**Comment by wytrych** [comment]
It is because the test is looking for an `h4` so you need to update the test to look for `span.title` instead, or just `.title` to be more future proof

**Comment by Minglee01** [comment]
Im gonna merge this. @wytrych  we tried `.title` i dont think this available at that point in the test

**Comment by wytrych** [comment]
That's because `jqlite` `find()` works only for tag names, `expect(this.elm[0].querySelectorAll('.title').length).toEqual(1);` would work and I encourage you to bring the test back - it's always better to fix the test instead of removing it.

**Pull request merged**
