### PR TITLE
Update info for 0.0.1 release

### PR DESCRIPTION
**Pull request by grahamgilchrist**
This is for an initial 0.0.1 release so that we can test the dependency install

### CODE REVIEW

**Comment by grahamgilchrist** [comment]
@wytrych @adam-thomas Pls review/merge. Also FYI the release instructions I added to the readme.

**Comment by grahamgilchrist** [comment]
I guess we'll need to add some python release instructions too?

**Comment by adam-thomas** [comment]
LGTM :)

I think there's a `make release` command?

**Comment by grahamgilchrist** [comment]
Added python release command

**Comment by adam-thomas** [comment]
Happy to merge :)

**Comment by grahamgilchrist** [comment]
I just need to fix travis which fell over due to moving the npm install location

**Comment by adam-thomas** [comment]
Fair :)

**Comment by adam-thomas** [comment]
Travis looks like it's going to be happy now :)

**Pull request merged**
