### PR TITLE
Add proper POST serialization

### PR DESCRIPTION
**Pull request by adam-thomas**
* Add validation to the serializer.
* Update the API description for POST to reflect what the serializer actually does.
* Test.

@incuna/backend review please?

cc @wytrych, the API description changed again :P

### CODE REVIEW

**Comment by wytrych** [comment]
Thanks for letting me know

**Comment by adam-thomas** [comment]
No worries :)

**Comment by NoLogo** [comment]
LGTM

**Comment by adam-thomas** [comment]
Thanks!

**Comment by adam-thomas** [comment]
Any other comments?

**Pull request merged**
