### PR TITLE
Add serializer field generators

### PR DESCRIPTION
**Pull request by adam-thomas**
@incuna/backend review please? :)

### CODE REVIEW

**Comment by wytrych** [comment]
Are you using the api description from here? https://github.com/incuna/ipsen-optimise/pull/14 It would be really good to have this in this project actually. I want to write tests against it, would be great if the backend was using that too, so we don't fall out of sync

**Comment by adam-thomas** [comment]
Not deliberately.  I can update the API description with whatever the serializer fields output.  I'm not sure the `legend` field is in there by default.

**Comment by wytrych** [comment]
Well, if we don't use the api-description then we'll get into trouble sooner or later. I would really advocate for it, it has proven to work well previously.

**Comment by adam-thomas** [comment]
How set in stone is it meant to be?

**Comment by wytrych** [comment]
Well, more than less I think, but at least if we have the api-description in this project and we're both testing against it, then if you need to update it a little bit I will know I have to fix my code too. If this is meant to be a library then it should really be ready to use out of the box, and the api-description can come a long way to help with that.

**Comment by adam-thomas** [comment]
I'll do it after this PR is merged.

**Comment by wytrych** [comment]
Cool thanks

**Comment by KevinEtienne** [comment]
Looks really cool :) We have a generator now for API fields.

**Comment by adam-thomas** [comment]
Thanks @KevinEtienne :)

**Pull request merged**
